### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by fabtl100** [fabtl100/Jacuzzi#1]
This is a to-do list for the first week of work with the Jacuzzi project, it will consist of the work needed to be done before the interview with the client.

- [ ] Create 3 different mockups for the display of the seller section
- [ ] Create 3 different mockups for the display of the products section 
- [ ] Finish documentation for the interview (interview protocol and project description)

**Comment by fabtl100** [comment]
- The first 3 mockups will be for the page of the seller, the idea is to have a profile page for the sellers, in which we will display the sellers name, the products they sell with their respective prices and other information the client may want to display in this page.
- The next 3 mockups will be for the buying page, we can implement something like a news feed where the users will see all products and choose which one to buy if the option to buy beforehand is available, or just to see the product and the price. (This page will display only the product of the currently active sellers)
